WebStack/Presentation/AgileEAP.Web/Models/Install/InstallModel.cs
using System.Web.Mvc;
using FluentValidation.Attributes;
using AgileEAP.MVC;
using AgileEAP.Web.Validators.Install;

namespace AgileEAP.Web.Models.Install
{
    [Validator(typeof(InstallValidator))]
    public class InstallModel : AgileEAPModel
    {
        [AllowHtml]
        public string AdminEmail { get; set; }
        [AllowHtml]
        public string AdminPassword { get; set; }
        [AllowHtml]
        public string ConfirmPassword { get; set; }


        [AllowHtml]
        public string DatabaseConnectionString { get; set; }
        public string DataProvider { get; set; }
        //SQL Server properties
        public string SqlConnectionInfo { get; set; }
        [AllowHtml]
        public string SqlServerName { get; set; }
        [AllowHtml]
        public string SqlDatabaseName { get; set; }
        [AllowHtml]
        public string SqlServerUsername { get; set; }
        [AllowHtml]
        public string SqlServerPassword { get; set; }
        public string SqlAuthenticationType { get; set; }
        public bool SqlServerCreateDatabase { get; set; }



        public bool InstallSampleData { get; set; }
    }
}

WebStack/Presentation/AgileEAP.Web/Controllers/InstallController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Threading;
using System.Web.Hosting;
using System.Web.Mvc;
using AgileEAP.Core;
using AgileEAP.Core.Data;
using AgileEAP.Core.Infrastructure;
using AgileEAP.Core.Plugins;
using AgileEAP.MVC.Controllers;
using AgileEAP.Web.Models.Install;

namespace AgileEAP.Web.Controllers
{
    public class InstallController : BaseController
    {
        public InstallController(IWorkContext workContext, IRepository<string> repository)
            : base(workContext, repository)
        { }

        #region Utilities

        /// <summary>
        /// Checks if the specified database exists, returns true if database exists
        /// </summary>
        /// <param name="connectionString">Connection string</param>
        /// <returns>Returns true if the database exists.</returns>
        private bool sqlServerDatabaseExists(string connectionString)
        {
            try
            {
                //just try to connect
                using (var conn = new SqlConnection(connectionString))
                {
                    conn.Open();
                }
                return true;
            }
            catch
            {
                return false;
            }
        }

        /// <summary>
        /// Creates a database on the server.
        /// </summary>
        /// <param name="connectionString">Connection string</param>
        /// <returns>Error</returns>
        private string createDatabase(string connectionString)
        {
            try
            {
                //parse database name
                var builder = new SqlConnectionStringBuilder(connectionString);
                var databaseName = builder.InitialCatalog;
                //now create connection string to 'master' dabatase. It always exists.
                builder.InitialCatalog = "master";
                var masterCatalogConnectionString = builder.ToString();
                string query = string.Format("CREATE DATABASE [{0}] COLLATE SQL_Latin1_General_CP1_CI_AS", databaseName);

                using (var conn = new SqlConnection(masterCatalogConnectionString))
                {
                    conn.Open();
                    using (var command = new SqlCommand(query, conn))
                    {
                        command.ExecuteNonQuery();
                    }
                }

                return string.Empty;
            }
            catch (Exception ex)
            {
                return string.Format("An error occured when creating database: {0}", ex.Message);
            }
        }

        /// <summary>
        /// Check permissions
        /// </summary>
        /// <param name="path">Path</param>
        /// <param name="checkRead">Check read</param>
        /// <param name="checkWrite">Check write</param>
        /// <param name="checkModify">Check modify</param>
        /// <param name="checkDelete">Check delete</param>
        /// <returns>Resulr</returns>
        private bool checkPermissions(string path, bool checkRead, bool checkWrite, bool checkModify, bool checkDelete)
        {
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            bool flag6 = false;
            bool flag7 = false;
            bool flag8 = false;
            WindowsIdentity current = WindowsIdentity.GetCurrent();
            System.Security.AccessControl.AuthorizationRuleCollection rules = null;
            try
            {
                rules = Directory.GetAccessControl(path).GetAccessRules(true, true, typeof(SecurityIdentifier));
            }
            catch
            {
                return true;
            }
            try
            {
                foreach (FileSystemAccessRule rule in rules)
                {
                    if (!current.User.Equals(rule.IdentityReference))
                    {
                        continue;
                    }
                    if (AccessControlType.Deny.Equals(rule.AccessControlType))
                    {
                        if ((FileSystemRights.Delete & rule.FileSystemRights) == FileSystemRights.Delete)
                            flag4 = true;
                        if ((FileSystemRights.Modify & rule.FileSystemRights) == FileSystemRights.Modify)
                            flag3 = true;

                        if ((FileSystemRights.Read & rule.FileSystemRights) == FileSystemRights.Read)
                            flag = true;

                        if ((FileSystemRights.Write & rule.FileSystemRights) == FileSystemRights.Write)
                            flag2 = true;

                        continue;
                    }
                    if (AccessControlType.Allow.Equals(rule.AccessControlType))
                    {
                        if ((FileSystemRights.Delete & rule.FileSystemRights) == FileSystemRights.Delete)
                        {
                            flag8 = true;
                        }
                        if ((FileSystemRights.Modify & rule.FileSystemRights) == FileSystemRights.Modify)
                        {
                            flag7 = true;
                        }
                        if ((FileSystemRights.Read & rule.FileSystemRights) == FileSystemRights.Read)
                        {
                            flag5 = true;
                        }
                        if ((FileSystemRights.Write & rule.FileSystemRights) == FileSystemRights.Write)
                        {
                            flag6 = true;
                        }
                    }
                }
                foreach (IdentityReference reference in current.Groups)
                {
                    foreach (FileSystemAccessRule rule2 in rules)
                    {
                        if (!reference.Equals(rule2.IdentityReference))
                        {
                            continue;
                        }
                        if (AccessControlType.Deny.Equals(rule2.AccessControlType))
                        {
                            if ((FileSystemRights.Delete & rule2.FileSystemRights) == FileSystemRights.Delete)
                                flag4 = true;
                            if ((FileSystemRights.Modify & rule2.FileSystemRights) == FileSystemRights.Modify)
                                flag3 = true;
                            if ((FileSystemRights.Read & rule2.FileSystemRights) == FileSystemRights.Read)
                                flag = true;
                            if ((FileSystemRights.Write & rule2.FileSystemRights) == FileSystemRights.Write)
                                flag2 = true;
                            continue;
                        }
                        if (AccessControlType.Allow.Equals(rule2.AccessControlType))
                        {
                            if ((FileSystemRights.Delete & rule2.FileSystemRights) == FileSystemRights.Delete)
                                flag8 = true;
                            if ((FileSystemRights.Modify & rule2.FileSystemRights) == FileSystemRights.Modify)
                                flag7 = true;
                            if ((FileSystemRights.Read & rule2.FileSystemRights) == FileSystemRights.Read)
                                flag5 = true;
                            if ((FileSystemRights.Write & rule2.FileSystemRights) == FileSystemRights.Write)
                                flag6 = true;
                        }
                    }
                }
                bool flag9 = !flag4 && flag8;
                bool flag10 = !flag3 && flag7;
                bool flag11 = !flag && flag5;
                bool flag12 = !flag2 && flag6;
                bool flag13 = true;
                if (checkRead)
                {
                    flag13 = flag13 && flag11;
                }
                if (checkWrite)
                {
                    flag13 = flag13 && flag12;
                }
                if (checkModify)
                {
                    flag13 = flag13 && flag10;
                }
                if (checkDelete)
                {
                    flag13 = flag13 && flag9;
                }
                return flag13;
            }
            catch (IOException)
            {
            }
            return false;
        }

        /// <summary>
        /// Create contents of connection strings used by the SqlConnection class
        /// </summary>
        /// <param name="trustedConnection">Avalue that indicates whether User ID and Password are specified in the connection (when false) or whether the current Windows account credentials are used for authentication (when true)</param>
        /// <param name="serverName">The name or network address of the instance of SQL Server to connect to</param>
        /// <param name="databaseName">The name of the database associated with the connection</param>
        /// <param name="userName">The user ID to be used when connecting to SQL Server</param>
        /// <param name="password">The password for the SQL Server account</param>
        /// <param name="timeout">The connection timeout</param>
        /// <returns>Connection string</returns>
        private string createConnectionString(bool trustedConnection,
            string serverName, string databaseName, string userName, string password, int timeout = 0)
        {
            var builder = new SqlConnectionStringBuilder();
            builder.IntegratedSecurity = trustedConnection;
            builder.DataSource = serverName;
            builder.InitialCatalog = databaseName;
            if (!trustedConnection)
            {
                builder.UserID = userName;

WebStack/Presentation/AgileEAP.Web/Areas/Install/Views/Install/CreateUser.cshtml
@model Umbraco.Cms.Web.Model.Install.CreateNewUserModel
@{
    ViewBag.ActiveIndex = 2;
}
<!-- create box -->
<div class="tab main-tabinfo">
    <div class="container">
        <h1>
            Create User</h1>
        <div class="create-hold">
            <p>
                You can now setup a new admin user to log into Umbraco, we recommend using a stong
                password for this (a password which is more than 4 characters and contains a mix
                of letters, numbers and symbols). Please make a note of the chosen password.</p>
            <p>
                The password can be changed once you have completed the installation and logged
                into the admin interface.</p>
        </div>
    </div>
    <div class="database-hold">
        @using (Html.BeginForm("CreateUser", "Install", FormMethod.Post))
        {
            <fieldset>
                <div class="container">
                    <div class="instruction-hold">
                        <div class="row">
                            @Html.ValidationMessageFor(x => x.Name)
                            @Html.LabelFor(x => x.Name, "Name:")
                            <span>
                                @Html.TextBoxFor(x => x.Name, new { @class = "text" })
                            </span>
                        </div>
                        <div class="row">
                            @Html.ValidationMessageFor(x => x.Email)
                            @Html.LabelFor(x => x.Email, "Email:")
                            <span>
                                @Html.TextBoxFor(x => x.Email, new { @class = "text" })
                            </span>
                        </div>
                        <div class="row">
                            @Html.ValidationMessageFor(x => x.Username)
                            @Html.LabelFor(x => x.Username, "Username:")
                            <span>
                                @Html.TextBoxFor(x => x.Username, new { @class = "text" })
                            </span>
                        </div>
                        <div class="row" style="height: 35px; overflow: hidden;">
                            @Html.ValidationMessageFor(x => x.Password)
                            @Html.LabelFor(x => x.Password, "Password:")
                            <span>
                                @Html.PasswordFor(x => x.Password, new { @class = "text password" })
                            </span>
                        </div>
                        <div class="row">
                            @Html.ValidationMessageFor(x => x.ConfirmPassword)
                            @Html.LabelFor(x => x.ConfirmPassword, "Confirm Password:")
                            <span>
                                @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "text" })
                            </span>
                        </div>
                        <div class="check-hold">
                            @Html.CheckBoxFor(x => x.SignUpForNewsletter)
                            @Html.LabelFor(x => x.SignUpForNewsletter, "Sign up for our monthly newsletter?")
                        </div>
                    </div>
                </div>
                <footer class="btn-box">
                    <div class="t">
                        &nbsp;</div>
                    <a class="btn-create submit" href="#"><span>Create user</span></a>
                </footer>
            </fieldset>
        }
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        $("a.submit").click(function () {
            $('form').submit();
        });
        
        jQuery("input.password").passStrength({
            shortPass: "invalidaing",
            badPass: "invalidaing",
            goodPass: "validaing",
            strongPass: "validaing",
            baseStyle: "basevalidaing",
            userid: jQuery("#ctl09_tb_login").val(),
            messageloc: 1
        });
    });
</script>

WebStack/Presentation/AgileEAP.Web/Areas/Install/Views/Install/Database.cshtml
@model Umbraco.Cms.Web.Model.Install.DatabaseInstallModel
@{
    ViewBag.ActiveIndex = 1;
}
<!-- database box -->
<div class="tab main-tabinfo">
    <div class="container">
        <h1>
            Database configuration</h1>       
        <p>
            <strong>To complete this step you will either need a blank database or, if you do not
                have a blank database available, choose the SQL CE 4 embedded database (This is
                the recommended approach for first time users or if you are unsure).</strong></p>
        <p>
            If you are not using the SQL CE 4 embedded database you will need the connection
            details for your database, such as the &quot;connection string&quot;. You may need
            to contact your system administrator or web host for this information.</p>
    </div>
    <!-- database -->
    <div class="database-hold">
        @using (Html.BeginForm("Database", "Install", FormMethod.Post))
        {
            <fieldset>
                <div class="step">
                    <div class="container">
                        <p>
                            <strong>1. Select which database option best fits you:</strong>
                        </p>
                        <ul>
                            <li>
                                <input type="radio" id="databaseOptionBlank" name="database" value="blank" />
                                <label for="databaseOptionBlank">
                                    I already have a blank SQL Server <em>2008</em> database</label>
                            </li>
                            <li>
                                <input type="radio" id="databaseOptionEmbedded" name="database" value="embedded" />
                                <label for="databaseOptionEmbedded">
                                    I want to use SQL CE 4, a free, quick-and-simple embedded database</label>
                            </li>
                            
                            <li>
                                <input type="radio" id="databaseOptionAdvanced" name="database" value="advanced" />
                                <label for="databaseOptionAdvanced">
                                    I'm an advanced user, let me put in the connection string</label>
                            </li>
                           
                            <li>
                                <input type="radio" id="databaseOptionHelp" name="database" value="help" />
                                <label for="databaseOptionHelp">
                                    I need help</label>
                            </li>
                        </ul>
                    </div>
                </div>
                @Html.HiddenFor(x => x.DatabaseType)
                <!-- database options -->
                <div id="database-options">
                    <!-- blank option -->
                    <div id="database-blank" class="database-option">
                        <div class="step">
                            <div class="container">
                                <p>
                                    <strong>2. Now choose your database type below.</strong></p>
                                <div class="select">
                                    <select id="databaseDropDown" class="sel">
                                        <option value="">Please choose</option>
                                        <option selected="selected" value="MSSQL">Microsoft SQL Server 2008</option>
                                        <!--<option value="MySQL">MySQL</option>-->
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="step" id="database-blank-inputs">
                            <div class="container">
                                <p class="instructionText">
                                    <strong>3. Connection details:</strong> Please fill out the connection information
                                    for your database.</p>
                                <div class="instruction-hold">
                                    <div class="row sql" style="display: block;">
                                        @Html.ValidationMessageFor(x => x.Server)
                                        @Html.LabelFor(x => x.Server, "Server:")
                                        <span>
                                            @Html.TextBoxFor(x => x.Server, new { @class = "text" })
                                        </span>
                                    </div>
                                    <div class="row sql" style="display: block;">
                                        @Html.ValidationMessageFor(x => x.DatabaseName)
                                        @Html.LabelFor(x => x.DatabaseName, "Database name:")
                                        <span>
                                            @Html.TextBoxFor(x => x.DatabaseName, new { @class = "text" })
                                        </span>
                                    </div>
                                    <div class="row sql" style="display: block;">
                                        @Html.ValidationMessageFor(x => x.Username)
                                        @Html.LabelFor(x => x.Username, "Username:")
                                        <span>
                                            @Html.TextBoxFor(x => x.Username, new { @class = "text" })
                                        </span>
                                    </div>
                                    <div class="row sql" style="display: block;">
                                        @Html.ValidationMessageFor(x => x.Password)
                                        @Html.LabelFor(x => x.Password, "Password:")
                                        <span>
                                            @Html.PasswordFor(x => x.Password, new { @class = "text", autocomplete = "off" })
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <!-- btn box -->
                        </div>
                    </div>
                    <!-- embedded option -->
                    <div id="database-embedded" class="database-option">
                        <div class="step">
                            <div class="container">
                                <p class="instructionText">
                                    <strong>2. Simple file-based database:</strong></p>
                                <div class="instruction-hold">
                                    <div class="row embeddedError" style="display: none;">
                                        <p>
                                            <strong>Missing files:</strong> SQL CE 4 requires that you manually add the SQL
                                            CE 4 runtime to your Umbraco installation.<br />
                                            You can either use the following <a href="http://our.umbraco.org/wiki/install-and-setup/using-sql-ce-4-with-juno"
                                                target="_blank">instructions</a> on how to add SQL CE 4 or select another database
                                            type from the dropdown above.
                                        </p>
                                    </div>
                                    <div class="row embedded" style="display: none;">
                                        <p>
                                            <strong>Nothing to configure:</strong>SQL CE 4 does not require any configuration,
                                            simply click the "install" button to continue.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- advanced option -->
                    <div id="database-advanced" class="database-option">
                        <div class="step">
                            <div class="container">
                                <p>
                                    <strong>2. Connection details:</strong> Please fill out the connection information
                                    for your database (note: currently only supports SQL Server 2008 databases).</p>
                                <div class="instruction-hold">
                                    <div class="row custom">
                                        @Html.ValidationMessageFor(x => x.ConnectionString)
                                        @Html.LabelFor(x => x.ConnectionString, "Connection string:")
                                        <span class="textarea">
                                            @Html.TextAreaFor(x => x.ConnectionString, 2, 20, new { @class = "text textarea" })
                                        </span>
                                    </div>
                                    <div class="row custom check-hold">
                                        <p>
                                            Example: <tt>Data Source=.\SQLExpress; Initial Catalog=Umbraco-v5;Integrated Security=false;user=******;password=*****;</tt>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- help option -->
                    <div id="database-help" class="database-option">
                        <div class="step">
                            <div class="container">
                                <p>
                                    <strong>2. Getting a database setup for umbraco.</strong><br />
                                    For first time users, we recommend you select "quick-and-simple file-based database".
                                    This will install an easy to use database, that does not require any additional
                                    software to use.<br />
                                    Alternatively, you can install Microsoft SQL Server 2008 (including Express edition), which will require a bit more
                                    work to get up and running.<br />
                                    We have provided a step-by-step guide in the video instructions below.
                                </p>
                                <span class="btn-link"><a href="http://umbraco.org/getting-started" target="_blank">
                                    Open video instructions</a></span>
                            </div>
                        </div>
                    </div>
                    <footer class="btn-box installbtn">
                        <div class="t">&nbsp;</div>
                        <a class="single-tab submit btn-install"><span>install</span> </a>
                    </footer>
                </div>
            </fieldset>
        }
    </div>
</div>
<script type="text/javascript">
    var hasEmbeddedDlls = true;
    var currentVersion = '5.0.0';
    var configured = true;

    jQuery(document).ready(function () {

        $("a.submit").click(function () {
            $('form').submit();
        });

        var hiddenDbType = jQuery("#@Html.IdFor(x => x.DatabaseType)");

        $("#databaseDropDown").change(function () {
            if ($(this).val() != "") {
                hiddenDbType.val($(this).val());
            }
        });

        $("input[name='database']").change(function () {

            switch ($(this).val()) {
                case "blank":

                    $(".database-option").hide();
                    $("#database-blank").show();
                    $(".installbtn").show();

                    hiddenDbType.val("MSSQL");

                    break;
                case "embedded":
                    $(".database-option").hide();
                    $("#database-embedded").show();

                    if (!hasEmbeddedDlls) {
                        $('.embeddedError').show();
                        $(".installbtn").hide();
                    }
                    else {
                        $('.embedded').show();
                        $(".installbtn").show();
                    }

                    hiddenDbType.val("SQLCE");

                    break;
                case "advanced":
                    $(".database-option").hide();
                    $("#database-advanced").show();
                    $(".installbtn").show();

                    hiddenDbType.val("Custom");

                    break;
                case "help":
                    $(".database-option").hide();
                    $("#database-help").show();
                    $(".installbtn").hide();
                    break;
            }


        });

        if (hiddenDbType.val() == "Custom") {
            $('#databaseOptionAdvanced').click();
            $('#databaseOptionAdvanced').change();
        }
        else {
            $('#databaseOptionBlank').click();
            $('#databaseOptionBlank').change();
        }


    });

</script>

WebStack/Presentation/AgileEAP.Web/Areas/Install/Views/Install/DatabaseInstall.cshtml
@using Umbraco.Cms.Web.Mvc.Controllers.BackOffice;
@{
    ViewBag.ActiveIndex = 1;
    Layout = "_RestartAppLayout.cshtml";
    ViewBag.Title = "Installing Umbraco database";
    ViewBag.Message = "The Umbraco database is being configured. This process populates your chosen database with a blank Umbraco instance.";
    
    ViewBag.NextButtonUrl = Url.Action("CreateUser", "Install");
    ViewBag.PrevButtonUrl = Url.Action("Database", "Install");
    ViewBag.GetProgressUrl = Url.Action("PerformInstall", "Install");
    ViewBag.RestartUrl = Url.Action("PerformRecycleApplication", "Install");
}

WebStack/Presentation/AgileEAP.Web/Areas/Install/Views/Install/Index.cshtml
@{
    ViewBag.ActiveIndex = 0;
}
<!-- welcome box -->
<div class="tab main-tabinfo">
    <div class="container">
        <h1>
            Welcome to the Umbraco installation</h1>
        <h2>
            Thanks for downloading the Umbraco CMS installer.
        </h2>
        <p>
            You are just a few minutes away from getting up and running. The installer will
            take you through the following process:-</p>
        <ul class="text-list">
            <li><strong>1.</strong><span>Set up a database. There are a number of options available
                such as MS SQL Server and MS SQL Express Edition or you may wish to use the
                Microsoft SQL CE 4 database. You may need to consult your web host or system administrator.</span></li>
            <li><strong>2.</strong><span>You can then choose to install one of our great starter
                kits and a skin.</span></li>
            <li><strong>3.</strong><span>But whatever you do, don't forget to become part of the
                Umbraco community, one of the friendliest developer communities you will find. It’s
                what makes Umbraco such a great product and so much fun to use.</span></li>
        </ul>
        <span class="enjoy">Enjoy!</span>
    </div>
    <!-- btn box -->
    <footer class="btn-box">
        <div class="t">
            &nbsp;</div>
        <a class="btn btn-get" href="@Url.Action("Database", "Install")"><span>Lets get started!</span></a>
    </footer>
</div>

WebStack/Presentation/AgileEAP.Web/Areas/Install/Views/Install/PostStarterKitInstall.cshtml
@using Umbraco.Framework
@model string
@{
    ViewBag.ActiveIndex = 3;
    Layout = "_RestartAppLayout.cshtml";
    ViewBag.Title = "Installing Starter kit";
    ViewBag.Message = "Please wait while the application restarts and the starter kit is configured.";
    ViewBag.NextButtonUrl = Url.Action("Finish", "Install");
    ViewBag.PrevButtonUrl = Url.Action("StarterKit", "Install");
    ViewBag.GetProgressUrl = Url.Action("RunPackageActions", "Install", new { id = Model });
    ViewBag.RestartUrl = Url.Action("PerformRecycleApplication", "Install");
}